name: Docker Build Service API Gateway

on:
  push:
    branches:
      - main
    paths:
      - functions/0002_api_gateway/**  # Only trigger if there are changes in this directory

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        run: |
          docker buildx build functions/0002_api_gateway --platform linux/amd64,linux/arm64 -t ghcr.io/${{ github.repository }}/api-gateway:latest --push
          
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
